
import * as identitykeys from '../identityDataKeys';
import * as keylist from '../keys';
import * as VDXF_Data from '../vdxfDataKeys';

export const friendlyName = (vdfxkey) => {

  if (vdfxkey in IdentityVdxfidMap) {

    return IdentityVdxfidMap[vdfxkey].name;

  } else {
    throw new Error("Unknown VDXF key");
  }
}

export const getIdentityDataType = (vdfxkey) => {
  
    if (vdfxkey in IdentityVdxfidMap) {
  
      return IdentityVdxfidMap[vdfxkey].type;
  
    } else {
      throw new Error("Unknown VDXF key");
    }
  }

export const IdentityVdxfidMap = {
  [identitykeys.IDENTITYDATA_FIRSTNAME.vdxfid]: { name: "First Name", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_LASTNAME.vdxfid]: { name: "Last Name", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_NATIONALITY.vdxfid]: { name: "Nationality", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_ATTESTOR.vdxfid]: { name: "Attestor ID", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_IDENTITY.vdxfid]: { name: "Identity", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_ID.vdxfid]: { name: "ID", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_USERID.vdxfid]: { name: "User ID", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_CREATEDAT.vdxfid]: { name: "Created at", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_COMPLETEDAT.vdxfid]: { name: "Completed at", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_PREVIOUSATTEMPTID.vdxfid]: { name: "Previous attempt ID", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_SHAREABLEURL.vdxfid]: { name: "Shareable URL", type: VDXF_Data.DataURLKeyName() },
  [identitykeys.IDENTITYDATA_TEMPLATEID.vdxfid]: { name: "Template ID", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_TEMPLATEVERSION.vdxfid]: { name: "Template Version", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_PHONENUMBER.vdxfid]: { name: "Phone Number", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_DATEOFBIRTH.vdxfid]: { name: "Date of Birth", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_OVER18.vdxfid]: { name: "Over 18", type: VDXF_Data.DataByteKeyName() },
  [identitykeys.IDENTITYDATA_OVER21.vdxfid]: { name: "Over 21", type: VDXF_Data.DataByteKeyName() },
  [identitykeys.IDENTITYDATA_OVER25.vdxfid]: { name: "Over 25", type: VDXF_Data.DataByteKeyName() },
  [identitykeys.IDENTITYDATA_IPADDRESS.vdxfid]: { name: "IP Address", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_EMAIL.vdxfid]: { name: "Email Address", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_HOMEADDRESS.vdxfid]: { name: "Home address", type: VDXF_Data.DataUint160Key() },
  [identitykeys.IDENTITYDATA_HOMEADDRESS_STREET1.vdxfid]: { name: "Street 1", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_HOMEADDRESS_STREET2.vdxfid]: { name: "Street 2", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_HOMEADDRESS_CITY.vdxfid]: { name: "City", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_HOMEADDRESS_REGION.vdxfid]: { name: "Region", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_HOMEADDRESS_POSTCODE.vdxfid]: { name: "Post Code", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_HOMEADDRESS_COUNTRY.vdxfid]: { name: "Country", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_IDNUMBER_VALUE.vdxfid]: { name: "ID Number", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_IDNUMBER_TYPE.vdxfid]: { name: "ID Type", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_STATUS.vdxfid]: { name: "Status", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_APPROVALS_ACCEPTEDTOS.vdxfid]: { name: "Accepted Terms and Conditions", type: VDXF_Data.DataByteKeyName() },
  [identitykeys.IDENTITYDATA_APPROVALS_VERIFIEDSMS.vdxfid]: { name: "SMS Verified", type: VDXF_Data.DataByteKeyName() },
  [identitykeys.IDENTITYDATA_APPROVALS_KYCCHECKED.vdxfid]: { name: "KYC Checked ok", type: VDXF_Data.DataByteKeyName() },
  [identitykeys.IDENTITYDATA_APPROVALS_DOCUMENTSVERIFIED.vdxfid]: { name: "Documents Verified", type: VDXF_Data.DataByteKeyName() },
  [identitykeys.IDENTITYDATA_APPROVALS_SELFIECHECKED.vdxfid]: { name: "Selfie Checked", type: VDXF_Data.DataByteKeyName() },
  [identitykeys.IDENTITYDATA_APPROVALS_WATCHLIST_OK.vdxfid]: { name: "Watchlist ok", type: VDXF_Data.DataByteKeyName() },
  [identitykeys.IDENTITYDATA_APPROVALS_RISKCHECKOK.vdxfid]: { name: "Riskcheck ok", type: VDXF_Data.DataByteKeyName() },
  [identitykeys.IDENTITYDATA_DRIVINGLICENCE.vdxfid]: { name: "Driving Licence", type: VDXF_Data.DataUint160Key() },
  [identitykeys.IDENTITYDATA_DRIVINGLICENCE_ORIGINAL_FRONT.vdxfid]: { name: "Driving Licence Front", type: VDXF_Data.DataURLKeyName() },
  [identitykeys.IDENTITYDATA_DRIVINGLICENCE_ORIGINAL_BACK.vdxfid]: { name: "Driving Licence Back", type: VDXF_Data.DataURLKeyName() },
  [identitykeys.IDENTITYDATA_DRIVINGLICENCE_CROPPED_FRONT.vdxfid]: { name: "Driving Licence Front", type: VDXF_Data.DataURLKeyName() },
  [identitykeys.IDENTITYDATA_DRIVINGLICENCE_CROPPED_BACK.vdxfid]: { name: "Driving Licence Back", type: VDXF_Data.DataURLKeyName() },
  [identitykeys.IDENTITYDATA_DRIVINGLICENCE_FACE.vdxfid]: { name: "Driving Licence Face", type: VDXF_Data.DataURLKeyName() },
  [identitykeys.IDENTITYDATA_DRIVINGLICENCE_IDNUMBER.vdxfid]: { name: "Driving Licence Number", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_DRIVINGLICENCE_CATEGORY.vdxfid]: { name: "Driving Licence Catagory", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_DRIVINGLICENCE_EXPIRATIONDATE.vdxfid]: { name: "Driving Licence expiry date", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_DRIVINGLICENCE_ISSUING_COUNTRY_MATCHED.vdxfid]: { name: "Driving Licence matches country", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_DRIVINGLICENCE_ISSUING_REGION.vdxfid]: { name: "Driving Licence issuing region", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_DRIVINGLICENCE_DATEOFBIRTH.vdxfid]: { name: "Driving Licence Date of Birth", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_DRIVINGLICENCE_ADDRESS.vdxfid]: { name: "Driving Licence Address", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_DRIVINGLICENCE_STREET1.vdxfid]: { name: "Driving Licence Street 1", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_DRIVINGLICENCE_CITY.vdxfid]: { name: "Driving Licence City", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_DRIVINGLICENCE_REGION.vdxfid]: { name: "Driving Licence Region", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_DRIVINGLICENCE_POSTCODE.vdxfid]: { name: "Driving Licence ZIP/Post Code", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_DRIVINGLICENCE_COUNTRY.vdxfid]: { name: "Driving Licence Country", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_DRIVINGLICENCE_MATCHED.vdxfid]: { name: "Driving Licence Matched all", type: VDXF_Data.DataByteKeyName() },
  [identitykeys.IDENTITYDATA_DRIVINGLICENCE_NAME_MATCHED.vdxfid]: { name: "Driving Licence name matched", type: VDXF_Data.DataByteKeyName() },
  [identitykeys.IDENTITYDATA_DRIVINGLICENCE_DATEOFBIRTH_MATCHED.vdxfid]: { name: "Driving Licence Date of Birth Matched", type: VDXF_Data.DataByteKeyName() },
  [identitykeys.IDENTITYDATA_SELFIECHECK_SUCCESS.vdxfid]: { name: "Selfie Check success", type: VDXF_Data.DataByteKeyName() },
  [identitykeys.IDENTITYDATA_SELFIECHECK_IMAGE.vdxfid]: { name: "Selfie Check image", type: VDXF_Data.DataURLKeyName() },
  [identitykeys.IDENTITYDATA_SELFIECHECK_VIDEO.vdxfid]: { name: "Selfie Check video", type: VDXF_Data.DataURLKeyName() },
  [identitykeys.IDENTITYDATA_SELFIECHECK_DRIVINGLICENCE_MATCH.vdxfid]: { name: "Selfie Driving Licence match", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_KYC_SUCCESS.vdxfid]: { name: "KYC Success", type: VDXF_Data.DataByteKeyName() },
  [identitykeys.IDENTITYDATA_KYC_ADDRESS_MATCHED.vdxfid]: { name: "KYC Address Matched", type: VDXF_Data.DataByteKeyName() },
  [identitykeys.IDENTITYDATA_KYC_TYPE.vdxfid]: { name: "KYC Type", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_KYC_NAME_MATCHED.vdxfid]: { name: "KYC Name Matched", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_KYC_DATEOFBIRTH_MATCHED.vdxfid]: { name: "KYC Date of Birth Matched", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_KYC_IDNUMBER_MATCHED.vdxfid]: { name: "KYC ID Matched", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_KYC_PHONENUMBER_MATCHED.vdxfid]: { name: "KYC Phone number matched", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_KYC_AREACODE_MATCHED.vdxfid]: { name: "KYC Areacode Matched", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_RISKCHECK_STATUS.vdxfid]: { name: "Risk Check Status", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_RISKCHECK_USERINTERACTIONS.vdxfid]: { name: "Risck Check User Interactions", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_RISKCHECK_FRAUDRINGOK.vdxfid]: { name: "Risk Check No Fraudring", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_RISKCHECK_BOTNOTDETECTED.vdxfid]: { name: "Risk Check bot free", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_EMAIL_ISDELIVERABLE.vdxfid]: { name: "Email address is deliverable", type: VDXF_Data.DataByteKeyName() },
  [identitykeys.IDENTITYDATA_EMAIL_BREACHCOUNT.vdxfid]: { name: "Email breach count", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_EMAIL_FIRSTBREACHEDAT.vdxfid]: { name: "Email first breach date", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_EMAIL_LASTBREACHEDAT.vdxfid]: { name: "Email last breach date", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_EMAIL_DOMAIN_REGISTEREDAT.vdxfid]: { name: "Email domain registered at", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_EMAIL_DOMAIN_FREEPROVIDER.vdxfid]: { name: "Email is free provider", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_EMAIL_DOMAIN_CUSTOM.vdxfid]: { name: "Email Domain is custom", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_EMAIL_DOMAIN_DISPOSABLE.vdxfid]: { name: "Email Domain Disposable", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_EMAIL_DOMAIN_TOPLEVEL_SUSPICIOUS.vdxfid]: { name: "Email top level Domain Suspicious", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_IDCARD.vdxfid]: { name: "ID Card", type: VDXF_Data.DataUint160Key() },
  [identitykeys.IDENTITYDATA_IDCARD_ORIGINAL_FRONT.vdxfid]: { name: "ID Card Front", type: VDXF_Data.DataURLKeyName() },
  [identitykeys.IDENTITYDATA_IDCARD_ORIGINAL_BACK.vdxfid]: { name: "ID Card Back", type: VDXF_Data.DataURLKeyName() },
  [identitykeys.IDENTITYDATA_IDCARD_CROPPED_FRONT.vdxfid]: { name: "ID Card Front", type: VDXF_Data.DataURLKeyName() },
  [identitykeys.IDENTITYDATA_IDCARD_CROPPED_BACK.vdxfid]: { name: "ID Card Back", type: VDXF_Data.DataURLKeyName() },
  [identitykeys.IDENTITYDATA_IDCARD_FACE.vdxfid]: { name: "ID Card Face", type: VDXF_Data.DataURLKeyName() },
  [identitykeys.IDENTITYDATA_IDCARD_IDNUMBER.vdxfid]: { name: "ID Card ID Number", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_IDCARD_CATEGORY.vdxfid]: { name: "ID Card Category", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_IDCARD_EXPIRATIONDATE.vdxfid]: { name: "ID Card Expiry date", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_IDCARD_ISSUING_COUNTRY_MATCHED.vdxfid]: { name: "ID Card Issuing Country Matched", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_IDCARD_ISSUING_REGION.vdxfid]: { name: "ID Card Issuing Region", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_IDCARD_DATEOFBIRTH.vdxfid]: { name: "ID Card Date of Birth", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_IDCARD_ADDRESS.vdxfid]: { name: "ID Card Address", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_IDCARD_ADDRESS_STREET1.vdxfid]: { name: "ID Card Street 1", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_IDCARD_ADDRESS_CITY.vdxfid]: { name: "ID Card City", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_IDCARD_ADDRESS_REGION.vdxfid]: { name: "ID Card Region", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_IDCARD_ADDRESS_POSTCODE.vdxfid]: { name: "ID Card Zip/Post Code", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_IDCARD_ADDRESS_COUNTRY.vdxfid]: { name: "ID Card Country", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_IDCARD_DOCUMENTVERIFICATION_MATCHED.vdxfid]: { name: "ID Card Matched", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_IDCARD_NAME_MATCHED.vdxfid]: { name: "ID Card Name Matched", type: VDXF_Data.DataByteKeyName() },
  [identitykeys.IDENTITYDATA_IDCARD_DATEOFBIRTHMATCHED.vdxfid]: { name: "ID Card Date of Birth Matched", type: VDXF_Data.DataByteKeyName() },
  [identitykeys.IDENTITYDATA_PASSPORT.vdxfid]: { name: "Passport", type: VDXF_Data.DataUint160Key() },
  [identitykeys.IDENTITYDATA_PASSPORT_ORIGINAL_FRONT.vdxfid]: { name: "Passport front", type: VDXF_Data.DataURLKeyName() },
  [identitykeys.IDENTITYDATA_PASSPORT_ORIGINAL_BACK.vdxfid]: { name: "Passport back", type: VDXF_Data.DataURLKeyName() },
  [identitykeys.IDENTITYDATA_PASSPORT_CROPPED_FRONT.vdxfid]: { name: "Passport front", type: VDXF_Data.DataURLKeyName() },
  [identitykeys.IDENTITYDATA_PASSPORT_CROPPED_BACK.vdxfid]: { name: "Passport back", type: VDXF_Data.DataURLKeyName() },
  [identitykeys.IDENTITYDATA_PASSPORT_FACE.vdxfid]: { name: "Passport face", type: VDXF_Data.DataURLKeyName() },
  [identitykeys.IDENTITYDATA_PASSPORT_IDNUMBER.vdxfid]: { name: "Passport ID Number", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_PASSPORT_CATEGORY.vdxfid]: { name: "Passport Category", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_PASSPORT_EXPIRATIONDATE.vdxfid]: { name: "Passport expiry date", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_PASSPORT_ISSUING_COUNTRY_MATCHED.vdxfid]: { name: "Passport issuing country matched", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_PASSPORT_ISSUING_REGION.vdxfid]: { name: "Passport issuing region matched", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_PASSPORT_DATEOFBIRTH.vdxfid]: { name: "Passport date of birth", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_PASSPORT_ADDRESS.vdxfid]: { name: "Passport address", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_PASSPORT_ADDRESS_STREET1.vdxfid]: { name: "Passport street 1", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_PASSPORT_ADDRESS_CITY.vdxfid]: { name: "Passport city", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_PASSPORT_ADDRESS_REGION.vdxfid]: { name: "Passport region", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_PASSPORT_ADDRESS_POSTCODE.vdxfid]: { name: "Passport zip/post code", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_PASSPORT_ADDRESS_COUNTRY.vdxfid]: { name: "Passport country", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_PASSPORT_DOCUMENTVERIFICATION_MATCHED.vdxfid]: { name: "Passport matched", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_PASSPORT_NAME_MATCHED.vdxfid]: { name: "Passport Name Matched", type: VDXF_Data.DataByteKeyName() },
  [identitykeys.IDENTITYDATA_PASSPORT_DATEOFBIRTHMATCHED.vdxfid]: { name: "Passport date of birth matched", type: VDXF_Data.DataByteKeyName() },
  [identitykeys.IDENTITYDATA_RESIDENCEPERMIT.vdxfid]: { name: "Residence Permit", type: VDXF_Data.DataUint160Key() },
  [identitykeys.IDENTITYDATA_RESIDENCEPERMIT_ORIGINAL_FRONT.vdxfid]: { name: "Residence Permit front", type: VDXF_Data.DataURLKeyName() },
  [identitykeys.IDENTITYDATA_RESIDENCEPERMIT_ORIGINAL_BACK.vdxfid]: { name: "Residence Permit back", type: VDXF_Data.DataURLKeyName() },
  [identitykeys.IDENTITYDATA_RESIDENCEPERMIT_CROPPED_FRONT.vdxfid]: { name: "Residence Permit front", type: VDXF_Data.DataURLKeyName() },
  [identitykeys.IDENTITYDATA_RESIDENCEPERMIT_CROPPED_BACK.vdxfid]: { name: "Residence Permit back", type: VDXF_Data.DataURLKeyName() },
  [identitykeys.IDENTITYDATA_RESIDENCEPERMIT_FACE.vdxfid]: { name: "Residence Permit face", type: VDXF_Data.DataURLKeyName() },
  [identitykeys.IDENTITYDATA_RESIDENCEPERMIT_IDNUMBER.vdxfid]: { name: "Residence Permit ID Number", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_RESIDENCEPERMIT_CATEGORY.vdxfid]: { name: "Residence Permit category", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_RESIDENCEPERMIT_EXPIRATIONDATE.vdxfid]: { name: "Residence Permit expiry date", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_RESIDENCEPERMIT_ISSUING_COUNTRY_MATCHED.vdxfid]: { name: "Residence Permit issuing country matched", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_RESIDENCEPERMIT_ISSUING_REGION.vdxfid]: { name: "Residence Permit issuing region matched", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_RESIDENCEPERMIT_DATEOFBIRTH.vdxfid]: { name: "Residence Permit date of birth", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_RESIDENCEPERMIT_ADDRESS.vdxfid]: { name: "Residence Permit Address", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_RESIDENCEPERMIT_ADDRESS_STREET1.vdxfid]: { name: "Residence Permit Street 1", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_RESIDENCEPERMIT_ADDRESS_CITY.vdxfid]: { name: "Residence Permit City", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_RESIDENCEPERMIT_ADDRESS_REGION.vdxfid]: { name: "Residence Permit Region", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_RESIDENCEPERMIT_ADDRESS_POSTCODE.vdxfid]: { name: "Residence Permit Zip/Post code", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_RESIDENCEPERMIT_ADDRESS_COUNTRY.vdxfid]: { name: "Residence Permit Country", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_RESIDENCEPERMIT_DOCUMENTVERIFICATION_MATCHED.vdxfid]: { name: "Residence Permit Matched", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_RESIDENCEPERMIT_NAME_MATCHED.vdxfid]: { name: "Residence Permit name matched", type: VDXF_Data.DataByteKeyName() },
  [identitykeys.IDENTITYDATA_RESIDENCEPERMIT_DATEOFBIRTHMATCHED.vdxfid]: { name: "Residence Permit date of birth matched", type: VDXF_Data.DataByteKeyName() },
  [identitykeys.IDENTITYDATA_RESIDENTCARD.vdxfid]: { name: "Resident Card", type: VDXF_Data.DataUint160Key() },
  [identitykeys.IDENTITYDATA_RESIDENTCARD_ORIGINAL_FRONT.vdxfid]: { name: "Resident Card Front", type: VDXF_Data.DataURLKeyName() },
  [identitykeys.IDENTITYDATA_RESIDENTCARD_ORIGINAL_BACK.vdxfid]: { name: "Resident Card Back", type: VDXF_Data.DataURLKeyName() },
  [identitykeys.IDENTITYDATA_RESIDENTCARD_CROPPED_FRONT.vdxfid]: { name: "Resident Card Front", type: VDXF_Data.DataURLKeyName() },
  [identitykeys.IDENTITYDATA_RESIDENTCARD_CROPPED_BACK.vdxfid]: { name: "Resident Card Back", type: VDXF_Data.DataURLKeyName() },
  [identitykeys.IDENTITYDATA_RESIDENTCARD_FACE.vdxfid]: { name: "Resident Card Face", type: VDXF_Data.DataURLKeyName() },
  [identitykeys.IDENTITYDATA_RESIDENTCARD_IDNUMBER.vdxfid]: { name: "Resident Card ID Number", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_RESIDENTCARD_CATEGORY.vdxfid]: { name: "Resident Card Category", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_RESIDENTCARD_EXPIRATIONDATE.vdxfid]: { name: "Resident Card Expiry Date", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_RESIDENTCARD_ISSUING_COUNTRY_MATCHED.vdxfid]: { name: "Resident Card Issuing Country Matched", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_RESIDENTCARD_ISSUING_REGION.vdxfid]: { name: "Resident Card Issuing Region", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_RESIDENTCARD_DATEOFBIRTH.vdxfid]: { name: "Resident Card date of birth", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_RESIDENTCARD_ADDRESS.vdxfid]: { name: "Resident Card address", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_RESIDENTCARD_ADDRESS_STREET1.vdxfid]: { name: "Resident Card Street 1", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_RESIDENTCARD_ADDRESS_CITY.vdxfid]: { name: "Resident Card City", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_RESIDENTCARD_ADDRESS_REGION.vdxfid]: { name: "Resident Card Region", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_RESIDENTCARD_ADDRESS_POSTCODE.vdxfid]: { name: "Resident Card Zip/Post Code", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_RESIDENTCARD_ADDRESS_COUNTRY.vdxfid]: { name: "Resident Card Country", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_RESIDENTCARD_DOCUMENTVERIFICATION_MATCHED.vdxfid]: { name: "Resident Card Matched", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_RESIDENTCARD_NAME_MATCHED.vdxfid]: { name: "Resident Card Name Matched", type: VDXF_Data.DataByteKeyName() },
  [identitykeys.IDENTITYDATA_RESIDENTCARD_DATEOFBIRTHMATCHED.vdxfid]: { name: "Resident Card date of birth Matched", type: VDXF_Data.DataByteKeyName() },
  [identitykeys.IDENTITYDATA_VISA.vdxfid]: { name: "Visa", type: VDXF_Data.DataUint160Key() },
  [identitykeys.IDENTITYDATA_VISA_ORIGINAL_FRONT.vdxfid]: { name: "Visa front", type: VDXF_Data.DataURLKeyName() },
  [identitykeys.IDENTITYDATA_VISA_ORIGINAL_BACK.vdxfid]: { name: "Visa back", type: VDXF_Data.DataURLKeyName() },
  [identitykeys.IDENTITYDATA_VISA_CROPPED_FRONT.vdxfid]: { name: "Visa front", type: VDXF_Data.DataURLKeyName() },
  [identitykeys.IDENTITYDATA_VISA_CROPPED_BACK.vdxfid]: { name: "Visa back", type: VDXF_Data.DataURLKeyName() },
  [identitykeys.IDENTITYDATA_VISA_FACE.vdxfid]: { name: "Visa face", type: VDXF_Data.DataURLKeyName() },
  [identitykeys.IDENTITYDATA_VISA_IDNUMBER.vdxfid]: { name: "Visa ID Number", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_VISA_CATEGORY.vdxfid]: { name: "Visa Category", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_VISA_EXPIRATIONDATE.vdxfid]: { name: "Visa expiry date", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_VISA_ISSUING_COUNTRY_MATCHED.vdxfid]: { name: "Visa issuing country matched", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_VISA_ISSUING_REGION.vdxfid]: { name: "Visa issuing region", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_VISA_DATEOFBIRTH.vdxfid]: { name: "Visa date of birth", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_VISA_ADDRESS.vdxfid]: { name: "Visa address", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_VISA_ADDRESS_STREET1.vdxfid]: { name: "Visa Street 1", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_VISA_ADDRESS_CITY.vdxfid]: { name: "Visa City", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_VISA_ADDRESS_REGION.vdxfid]: { name: "Visa Region", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_VISA_ADDRESS_POSTCODE.vdxfid]: { name: "Visa Zip/Post Code", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_VISA_ADDRESS_COUNTRY.vdxfid]: { name: "Visa Country", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_VISA_DOCUMENTVERIFICATION_MATCHED.vdxfid]: { name: "Visa document matched", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_VISA_NAME_MATCHED.vdxfid]: { name: "Visa name matched", type: VDXF_Data.DataByteKeyName() },
  [identitykeys.IDENTITYDATA_VISA_DATEOFBIRTHMATCHED.vdxfid]: { name: "Visa date of birth matched", type: VDXF_Data.DataByteKeyName() },
  [identitykeys.IDENTITYDATA_DOCUMENTVERIFICATION_ORIGINALFRONT.vdxfid]: { name: "Original Front", type: VDXF_Data.DataURLKeyName() },
  [identitykeys.IDENTITYDATA_DOCUMENTVERIFICATION_ORIGINALBACK.vdxfid]: { name: "Original Back", type: VDXF_Data.DataURLKeyName() },
  [identitykeys.IDENTITYDATA_DOCUMENTVERIFICATION_CROPPEDFRONT.vdxfid]: { name: "Cropped Front", type: VDXF_Data.DataURLKeyName() },
  [identitykeys.IDENTITYDATA_DOCUMENTVERIFICATION_CROPPEDBACK.vdxfid]: { name: "Cropped Back", type: VDXF_Data.DataURLKeyName() },
  [identitykeys.IDENTITYDATA_DOCUMENTVERIFICATION_FACE.vdxfid]: { name: "Face", type: VDXF_Data.DataURLKeyName() },
  [identitykeys.IDENTITYDATA_DOCUMENTVERIFICATION_IDNUMBER.vdxfid]: { name: "ID Number", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_DOCUMENTVERIFICATION_CATEGORY.vdxfid]: { name: "Category", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_DOCUMENTVERIFICATION_EXPIRATIONDATE.vdxfid]: { name: "Expiry Date", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_DOCUMENTVERIFICATION_ISSUINGCOUNTRY.vdxfid]: { name: "Issuing Country", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_DOCUMENTVERIFICATION_ISSUING_REGION.vdxfid]: { name: "Issuing Region", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_DOCUMENTVERIFICATION_DATEOFBIRTH.vdxfid]: { name: "Date of Birth", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_DOCUMENTVERIFICATION_ADDRESS.vdxfid]: { name: "Address", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_ADDRESS_STREET1.vdxfid]: { name: "Street 1", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_ADDRESS_STREET2.vdxfid]: { name: "Street 2", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_ADDRESS_CITY.vdxfid]: { name: "City", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_ADDRESS_REGION.vdxfid]: { name: "Region", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_ADDRESS_POSTCODE.vdxfid]: { name: "Zip/Postal Code", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_ADDRESS_COUNTRY.vdxfid]: { name: "Country", type: VDXF_Data.DataStringKey() },
  [identitykeys.IDENTITYDATA_DOCUMENTVERIFICATION_MATCHED.vdxfid]: { name: "Document Matched", type: VDXF_Data.DataByteKeyName() },
  [identitykeys.IDENTITYDATA_DOCUMENTVERIFICATION_NAME_MATCHED.vdxfid]: { name: "Name Matched", type: VDXF_Data.DataByteKeyName() },
  [identitykeys.IDENTITYDATA_DOCUMENTVERIFICATION_DATEOFBIRTHMATCHED.vdxfid]: { name: "Date of Birth Matched", type: VDXF_Data.DataByteKeyName() },
  [identitykeys.BANK_ACCOUNT.vdxfid]: { name: "Bank Account", type: VDXF_Data.DataUint160Key() },
  [identitykeys.IDENTITYDATA_DOCUMENTS_AND_IMAGES.vdxfid]: { name: "Official ID Documents", type: VDXF_Data.DataUint160Key() },
  [keylist.ATTESTATION_PROVISION_TYPE.vdxfid]: { name: "Attestation Type", type: VDXF_Data.DataStringKey() },
  [keylist.ATTESTATION_PROVISION_URL.vdxfid]: { name: "Attestation URL", type: VDXF_Data.DataURLKeyName() },
  [keylist.ATTESTATION_VIEW_RESPONSE.vdxfid]: { name: "Attestation View Response", type: VDXF_Data.DataStringKey()},
  [keylist.ATTESTATION_VIEW_REQUEST.vdxfid]: { name: "Attestation View Response", type: VDXF_Data.DataStringKey()},
  [keylist.PROFILE_DATA_VIEW_REQUEST.vdxfid]: { name: "Profile Data View Request", type: VDXF_Data.DataStringKey()},
};

